AGTPPE2/Controllers/MATERIELsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AGTPPE2;

namespace AGTPPE2.Controllers
{
    public class MATERIELsController : Controller
    {
        private BDDKNEntities db = new BDDKNEntities();

        // GET: MATERIELs
        public ActionResult Index()
        {
            var mATERIEL = db.MATERIEL.Include(m => m.TYPECONNEXION1).Include(m => m.UTILISATEUR);
            return View(mATERIEL.ToList());
        }

        // GET: MATERIELs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MATERIEL mATERIEL = db.MATERIEL.Find(id);
            if (mATERIEL == null)
            {
                return HttpNotFound();
            }
            return View(mATERIEL);
        }

        // GET: MATERIELs/Create
        public ActionResult Create()
        {
            ViewBag.typeConnexion = new SelectList(db.TYPECONNEXION, "typeConnexion1", "descriptionConnexion");
            ViewBag.idUtilisateur = new SelectList(db.UTILISATEUR, "idUtilisateur", "nomUtilisateur");
            return View();
        }

        // POST: MATERIELs/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "numeroSerieMateriel,emplacementMateriel,modeleMateriel,ipMateriel,typeIpMateriel,numInfologMateriel,celluleMateriel,etatMateriel,numeroChariot,idUtilisateur,typeConnexion")] MATERIEL mATERIEL)
        {
            if (ModelState.IsValid)
            {
                db.MATERIEL.Add(mATERIEL);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.typeConnexion = new SelectList(db.TYPECONNEXION, "typeConnexion1", "descriptionConnexion", mATERIEL.typeConnexion);
            ViewBag.idUtilisateur = new SelectList(db.UTILISATEUR, "idUtilisateur", "nomUtilisateur", mATERIEL.idUtilisateur);
            return View(mATERIEL);
        }

        // GET: MATERIELs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MATERIEL mATERIEL = db.MATERIEL.Find(id);
            if (mATERIEL == null)
            {
                return HttpNotFound();
            }
            ViewBag.typeConnexion = new SelectList(db.TYPECONNEXION, "typeConnexion1", "descriptionConnexion", mATERIEL.typeConnexion);
            ViewBag.idUtilisateur = new SelectList(db.UTILISATEUR, "idUtilisateur", "nomUtilisateur", mATERIEL.idUtilisateur);
            return View(mATERIEL);
        }

        // POST: MATERIELs/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "numeroSerieMateriel,emplacementMateriel,modeleMateriel,ipMateriel,typeIpMateriel,numInfologMateriel,celluleMateriel,etatMateriel,numeroChariot,idUtilisateur,typeConnexion")] MATERIEL mATERIEL)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mATERIEL).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.typeConnexion = new SelectList(db.TYPECONNEXION, "typeConnexion1", "descriptionConnexion", mATERIEL.typeConnexion);
            ViewBag.idUtilisateur = new SelectList(db.UTILISATEUR, "idUtilisateur", "nomUtilisateur", mATERIEL.idUtilisateur);
            return View(mATERIEL);
        }

        // GET: MATERIELs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MATERIEL mATERIEL = db.MATERIEL.Find(id);
            if (mATERIEL == null)
            {
                return HttpNotFound();
            }
            return View(mATERIEL);
        }

        // POST: MATERIELs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            MATERIEL mATERIEL = db.MATERIEL.Find(id);
            db.MATERIEL.Remove(mATERIEL);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AGTPPE2/Controllers/TICKETSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AGTPPE2;

namespace AGTPPE2.Controllers
{
    public class TICKETSController : Controller
    {
        private BDDKNEntities db = new BDDKNEntities();

        // GET: TICKETS
        public ActionResult Index()
        {
            var tICKETS = db.TICKETS.Include(t => t.CELLULE).Include(t => t.MATERIEL).Include(t => t.STATUT).Include(t => t.UTILISATEUR);
            return View(tICKETS.ToList());
        }

        // GET: TICKETS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TICKETS tICKETS = db.TICKETS.Find(id);
            if (tICKETS == null)
            {
                return HttpNotFound();
            }
            return View(tICKETS);
        }

        // GET: TICKETS/Create
        public ActionResult Create()
        {
            ViewBag.nomCellule = new SelectList(db.CELLULE, "nomCellule", "nomCellule");
            ViewBag.numeroSerieMateriel = new SelectList(db.MATERIEL, "numeroSerieMateriel", "emplacementMateriel");
            ViewBag.etatStatut = new SelectList(db.STATUT, "etatStatut", "etatStatut");
            ViewBag.idUtilisateur = new SelectList(db.UTILISATEUR, "idUtilisateur", "nomUtilisateur");
            return View();
        }

        // POST: TICKETS/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idTicket,emplacementMaterielTicket,typeMaterielTicket,descriptionIncident,dateCreationIncident,dateClotureIncident,idUtilisateur,numeroSerieMateriel,nomCellule,etatStatut")] TICKETS tICKETS)
        {
            if (ModelState.IsValid)
            {
                db.TICKETS.Add(tICKETS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.nomCellule = new SelectList(db.CELLULE, "nomCellule", "nomCellule", tICKETS.nomCellule);
            ViewBag.numeroSerieMateriel = new SelectList(db.MATERIEL, "numeroSerieMateriel", "emplacementMateriel", tICKETS.numeroSerieMateriel);
            ViewBag.etatStatut = new SelectList(db.STATUT, "etatStatut", "etatStatut", tICKETS.etatStatut);
            ViewBag.idUtilisateur = new SelectList(db.UTILISATEUR, "idUtilisateur", "nomUtilisateur", tICKETS.idUtilisateur);
            return View(tICKETS);
        }

        // GET: TICKETS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TICKETS tICKETS = db.TICKETS.Find(id);
            if (tICKETS == null)
            {
                return HttpNotFound();
            }
            ViewBag.nomCellule = new SelectList(db.CELLULE, "nomCellule", "nomCellule", tICKETS.nomCellule);
            ViewBag.numeroSerieMateriel = new SelectList(db.MATERIEL, "numeroSerieMateriel", "emplacementMateriel", tICKETS.numeroSerieMateriel);
            ViewBag.etatStatut = new SelectList(db.STATUT, "etatStatut", "etatStatut", tICKETS.etatStatut);
            ViewBag.idUtilisateur = new SelectList(db.UTILISATEUR, "idUtilisateur", "nomUtilisateur", tICKETS.idUtilisateur);
            return View(tICKETS);
        }

        // POST: TICKETS/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idTicket,emplacementMaterielTicket,typeMaterielTicket,descriptionIncident,dateCreationIncident,dateClotureIncident,idUtilisateur,numeroSerieMateriel,nomCellule,etatStatut")] TICKETS tICKETS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tICKETS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.nomCellule = new SelectList(db.CELLULE, "nomCellule", "nomCellule", tICKETS.nomCellule);
            ViewBag.numeroSerieMateriel = new SelectList(db.MATERIEL, "numeroSerieMateriel", "emplacementMateriel", tICKETS.numeroSerieMateriel);
            ViewBag.etatStatut = new SelectList(db.STATUT, "etatStatut", "etatStatut", tICKETS.etatStatut);
            ViewBag.idUtilisateur = new SelectList(db.UTILISATEUR, "idUtilisateur", "nomUtilisateur", tICKETS.idUtilisateur);
            return View(tICKETS);
        }

        // GET: TICKETS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TICKETS tICKETS = db.TICKETS.Find(id);
            if (tICKETS == null)
            {
                return HttpNotFound();
            }
            return View(tICKETS);
        }

        // POST: TICKETS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TICKETS tICKETS = db.TICKETS.Find(id);
            db.TICKETS.Remove(tICKETS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AGTPPE2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AGTPPE2/Views/Shared/_LayoutAdmin.cshtml
@{
    ViewBag.Title = "_LayoutAdmin";
}

<h2>_LayoutAdmin</h2>

AGTPPE2/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Application de gestion de tickets</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="jumbotron">
        <h1>Application de gestion de tickets</h1>
    </div>
    <!--
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div> -->
    <div class="navbar-collapse collapse">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                <li>@Html.ActionLink("Incidents en cours", "Create", "MATERIELs")</li>
                <li>@Html.ActionLink("Incidents clôturés", "Create", "MATERIELs")</li>
                <li>@Html.ActionLink("Déclarer un incident", "Create", "TICKETS")</li>
                <li>@Html.ActionLink("Inventaire", "Create", "MATERIELs")</li>
                <li>@Html.ActionLink("Utilisateur", "Create", "UTILISATEURs")</li>
                <li>@Html.ActionLink("Deconnexion", "Index")</li>
            </ul>
        </div>

    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year Kuehne + Nagel Artenay</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>